### ISSUE TITLE
Should be based on the cursor position

### ISSUE THREAD

**Issue by tobia** [gazugafan/vscode-indent-on-paste#13]
I don't know if this is to be considered a bug or if that's just how this extension works, but in other editors that indent on paste automatically (Sublime Text, Intellij IDEA, etc.) I can just copy a block of code, with its own indentation:

```
    try {
        println("Hello, World");
    } catch (Exception) {
        println("So long, and thanks for all the fish.");
    }
```

Then put my cursor somewhere else in the correct position:

```
        for (editor in editors) {
            if (editor sucks) {
                |
```

`|` is the cursor

Press Ctrl-V and the editor should do the following:

1. strip the minimum common margin from the contents of the clipboard;
2. add the indentation on the left of the cursor to every line of the block;
3. paste it.

The result should be:

```
        for (editor in editors) {
            if (editor sucks) {
                try {
                    println("Hello, World");
                } catch (Exception) {
                    println("So long, and thanks for all the fish.");
                }
                |
```

`|` is where the cursor ends up.

This extension does not seem to do that, which for me is a bug. 

(But then again, maybe it "works as indented" for the author?)

**Comment by gazugafan** [comment]
Sorry, this issue slipped under my radar... This is sort of how it works, but I decided to have the indentation algorithm match the indentation of the line *following* the insertion point. This allows it to work in a more language-agnostic way. So, it would work if you pasted into something like this, for example...
```
		for (editor in editors) {
			if (editor sucks) {	
				|
			}
```
... because it sees the following line is an ending block, and sets the new indentation one level greater than that. It does not take into account the current insertion point's indentation level. Here's another example that will also result in the same thing...

```
		for (editor in editors) {
			if (editor sucks) {	
	|
			}
```
... again, the algorithm checks the line following the insertion point and figures out the new indentation from there. However, if you pasted into something like this, it might not give you what you expect...
```
		for (editor in editors) {
			if (editor sucks)	
				|
		}
```
... but yeah, this is working as intended. If it was this, for example...
```
		for (editor in editors) {
			if (editor sucks)	
	|
		}
```
... and we wanted it to result in an indentation one greater than the `if`, then we would need to be looking at the line *before* the insertion point and trying to figure out if that line is a "starting block". Starting blocks are more difficult to identify because they usually contain more stuff (HTML attributes, conditions, etc etc) and there are more of them across languages.
