### ISSUE TITLE
Does it work with python?

### ISSUE THREAD

**Issue by canklot** [gazugafan/vscode-indent-on-paste#21]
I am having some problems in python when copy-pasting some code into a function. The first line is generally automatically indented but I had to manually indent other lines. Does this extension work with python?

**Comment by gazugafan** [comment]
It should adjust the indentation of the pasted code so that it matches the indentation level of the next non-blank line following the insertion point. There aren't any ending blocks in Python, though, so there's no way to detect if the pasted code should be indented *further* if the insertion point is at the end of a function or other block. For example...

```python
def my_function():
  |
  print("Hello from a function")

def another_function():
  print("Hello from other function")
```

If you paste at the | above, the code's indentation will be adjusted to level one (to match the level one indentation on the following print line).

```python
def my_function():
  print("Hello from a function")
  |

def another_function():
  print("Hello from other function")
```

If you paste at the | above, the code's indentation will be adjusted to level zero (to match the zero level indentation of the following def line). If this were a language with ending blocks, say PHP...

```php
function my_function() {
  echo "Hello from a function";
  |
}

function another_function() {
  echo "Hello from other function";
}
```

... then pasting at the | above would correctly indent to level one, because the following line is at level zero, but it's an ending block so we increase the indentation level by 1.

**Comment by Bobronium** [comment]
@gazugafan, hi! 

The way it could work:
*paste happen*
1. get clipboard
2. if clipboard.startswith(" "), goto step 5.   (don't change clipboard content)
3. get cursor position, count current indentation
4. indent current clipboard with indentation from step 3.
5. paste


I have no idea how to write proper JS, but in python it would look like this:

```py
import textwrap

def modify_clipboard_on_paste(column: int, line: str, clipboard: str) -> str:
    if clipboard.lstrip(" \t") != clipboard:   # do nothing if clipboard is already indented
        return clipboard
    before_cursor = line[:column]
    if before_cursor.lstrip():
        return clipboard
    
    return textwrap.indent(clipboard, prefix=before_cursor)
```

**Comment by gazugafan** [comment]
Wouldn't that just keep whatever indentation is already on the clipboard, though? The point of this is to re-indent the contents of the clipboard to match where you're pasting, right?

So, in this example...
```python
def my_function():
  print("Hello from a function")
  |

def another_function():
  print("Hello from other function")
```

If you paste something that contains 5 levels of indentation at the |, under your logic you would get...
```python
def my_function():
  print("Hello from a function")
            pasted content

def another_function():
  print("Hello from other function")
```

**Comment by Bobronium** [comment]
Well, it would, and it's exactly what I'm looking for.

Currently extension is unusable in python for the reasons you described above or, in short, because python "built different". It flattens the python code making it invalid:

##### clipboard content
```
def function_inside_the_function():
    print("Hello from other function")
```

```py
def my_function():
    print("Hello from a function")
    | <—— paste here
```
##### currently will result in
```py
def my_function():
    print("Hello from a function")
    def function_inside_the_function():
    print("Hello from other function")
```
##### should result in (with behaviour that I'm proposing)
```py
def my_function():
    print("Hello from a function")
    def function_inside_the_function():
        print("Hello from other function")
```

And with clipboard content that already indented, like this one:
```
    def function_inside_the_function():
        print("Hello from other function")
```
Extension should do nothing or dedent it, and then follow the same logic as described (the later should be configurable)


My proposal is about fixing current behaviour + still matching the indentation when possible.

**Comment by Bobronium** [comment]
Actually, you're pointing out a valid case that can be addressed, but will require more logic and understanding of python syntax.

As you can see here, PyCharm is able to handle such case as well as many others:

https://user-images.githubusercontent.com/36469655/169037903-71e7cfac-6b94-4c5c-acea-4a07ec7bfde0.MP4

But it requires more knowledge about the context and understanding of python syntax.

Though, simpler logic like I'm proposing also can be an improvement:
```py
import textwrap


def modify_clipboard_on_paste(column: int, line: str, clipboard: str) -> str:
    if clipboard.lstrip(" \t") != clipboard:
        if not column:
            # cursor is at the beginning of the line
            # don't modify clipboard
            return clipboard
        else:
            clipboard = textwrap.dedent(clipboard)

    before_cursor = line[:column]
    if before_cursor.lstrip():
        return clipboard

    return textwrap.indent(clipboard, prefix=before_cursor)
```

**Comment by gazugafan** [comment]
Right, but this behavior would really only apply to Python, and I'm not interested in fine-tuning the indentation algorithm for specific languages. What you're looking for is a full-on Python language server which understands Python and reformats code accordingly. I think Pylance does that?

**Comment by Bobronium** [comment]
Ack! 

No, Pylance doesn't do that, unfortunately. I guess, I'll try to write an extension myself then :)

**Comment by gazugafan** [comment]
Well damn :(
It seems like there must be a python language server for VS Code that already does this. I don't do much with python, though, so maybe I'm wrong :(

Feel free to use this extension as a starting point (unless you're going about writing a whole language server). If you're able to make it all work in a language-agnostic way, I'll be happy to take a PR :)
