### ISSUE TITLE
Is there a way to recognize that there is no line above copied code?

### ISSUE THREAD

**Issue by smoochy** [gazugafan/vscode-indent-on-paste#25]
Hi,

I wasn't exactly sure how to chose a proper title, hope the one I chose is ok.

I am aware of the limitations you wrote about in your readme. 
And as long as there a line above the one I want to copy, it works.

But what doesn't work is when I copy that:

![image](https://user-images.githubusercontent.com/34371932/232560556-8cea94a2-f0d2-42f3-80f2-46fd7a43db49.png)

As you can see, there is no line above, as it is the first line of the code (in that case in a Jupyter Notebook). When I copy and paste that piece of code, as you state in your readme, there is no indent in the paste.

![image](https://user-images.githubusercontent.com/34371932/232562595-32fe2343-e474-475c-9549-3549a64f8b93.png)

I was wondering, if there is a possibility, to check, if there is no line at all above the first line of the copied code. And if so, that you paste with proper indenting.

There is another extension, more specificially for Python ([Python Pase and Indent](https://github.com/sunhs/py-paste-indent)). When I disable your extension (and reload VSC) and have this other extension enabled, copy and pasting for that same piece of code works.
But I am not sure, if it only works because it is depending on setting up a keyboard shortcut.

Can you find something in their source which might help overcome the limitation?

If not, would it maybe be possible to add an option, where the user can chose, if he wants to be able to properly paste and indent, even if there is no line above which your extension depends on so far?

Like `PasteMode` with options `normal`and `risky`. Normal being the current behaviour and risky not checking if there is a line above for orientation and pasting anyways?

Cheers.

**Comment by gazugafan** [comment]
Unfortunately, there's not much that can be done here. The extension you mentioned probably has an understanding of Python and how the syntax works, so it's able to intelligently determine that what follows the first line should be indented (because the first line is the start of a class). Or it assumes you always copy an entire line with the indentation already included.

My extension is language agnostic. It has no language knowledge. All it sees is...
```
text
	text
		text
```

and without a line copied from above, there's no way to know if what you copied started with the indentation already included or not. You could have copied something like...
```
	print("line 1")
	if True:
		print("line 3")
```
... starting from the first line, but not including the first tab (starting with the "p" in "print"). If you did that, then what's on the clipboard is...
```
text
	text
		text
```
... which is the same as the first 3 lines in your example, but not the same indentation you'd want.

**Comment by smoochy** [comment]
Thank you for explaining into such detail.

I don't know, if this is a feasible thing to do: Would it be possible to enable a "plug-in" system for your extension? This way other users could hook into your extension enhancing it with more possibilities.

**Comment by gazugafan** [comment]
To be honest, I've switched to JetBrains, so I don't really use this extension anymore and not very interested in developing it into something bigger. Anything's possible, though! PRs welcome ;)
